name: Sync GitHub Issues and Pull Requests to Feishu Table

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  sync-to-feishu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get Feishu Access Token
      id: get_feishu_token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: |
        # Use APP_ID and APP_SECRET to get Feishu access token
        TENANT_ACCESS_TOKEN=$(curl -X POST -H 'Content-Type: application/json' \
          -d "{\"app_id\":\"$APP_ID\",\"app_secret\":\"$APP_SECRET\"}" \
          https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal)
        echo "TENANT_ACCESS_TOKEN=$TENANT_ACCESS_TOKEN" >> $GITHUB_OUTPUT
        
    - name: Sync Issue to Feishu
      if: github.event_name == 'issues'
      env:
        ISSUES_TABLE_ID: ${{ secrets.ISSUES_TABLE_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        ISSUE_CREATED_TIME: ${{ github.event.issue.created_at }}
        ISSUE_STATUS: ${{ github.event.issue.state }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        LAST_MODIFIED_TIME: ${{ github.event.issue.updated_at }}
      run: |
        # Use APP_TOKEN and ISSUES_TABLE_ID to write issue data to Feishu table
        curl -i -X POST 'https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$ISSUES_TABLE_ID/records' \
        -H 'Content-Type: application/json' \
        -d "{
          \"fields\": {
            \"IssueNumber\": \"$ISSUE_NUMBER\",
            \"IssueAuthor\": \"$ISSUE_AUTHOR\", 
            \"IssueCreatedTime\": \"$ISSUE_CREATED_TIME\",
            \"IssueStatus\": \"$ISSUE_STATUS\",
            \"IssueTitle\": \"$ISSUE_TITLE\",
            \"IssueDescription\": \"$ISSUE_DESCRIPTION\",
            \"LastModifiedTime\": \"$LAST_MODIFIED_TIME\"
          }
        }"
        
    - name: Sync Pull Request to Feishu  
      if: github.event_name == 'pull_request'
      env:
        PR_TABLE_ID: ${{ secrets.PR_TABLE_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        PR_CREATED_TIME: ${{ github.event.pull_request.created_at }}
        PR_STATUS: ${{ github.event.pull_request.state }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        LAST_MODIFIED_TIME: ${{ github.event.pull_request.updated_at }}
      run: |
        # Use APP_TOKEN and PR_TABLE_ID to write pull request data to Feishu table
        curl -i -X POST 'https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$PR_TABLE_ID/records' \
        -H 'Content-Type: application/json' \
        -d "{
          \"fields\": {
            \"PullRequestNumber\": \"$PR_NUMBER\",
            \"PullRequestAuthor\": \"$PR_AUTHOR\",
            \"PullRequestCreatedTime\": \"$PR_CREATED_TIME\", 
            \"IssueStatus\": \"$PR_STATUS\",
            \"PullRequestTitle\": \"$PR_TITLE\",
            \"PullRequestDescription\": \"$PR_DESCRIPTION\",
            \"LastModifiedTime\": \"$LAST_MODIFIED_TIME\"
          }
        }"

