name: Sync GitHub Issues and Pull Requests to Feishu Table

on:
  issues:
    types: [opened, closed, reopened, edited]
  pull_request:
    types: [opened, closed, reopened, edited]

jobs:
  sync-to-feishu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get Feishu App Access Token
      id: get_feishu_token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"app_id\":\"$APP_ID\",\"app_secret\":\"$APP_SECRET\"}" \
        https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal | \
        jq -r '.tenant_access_token' > feishu_app_token.txt
        echo "::set-output name=feishu_app_token::$(cat feishu_app_token.txt)"
        
    - name: Sync Issues to Feishu
      if: github.event_name == 'issues'
      env:
        FEISHU_APP_TOKEN: ${{ steps.get_feishu_token.outputs.feishu_app_token }}
        ISSUES_TABLE_ID: ${{ secrets.ISSUES_TABLE_ID }}
      run: |
        issue_number=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        issue_author=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
        issue_created_at=$(jq -r '.issue.created_at' "$GITHUB_EVENT_PATH")
        issue_status=$(jq -r '.issue.state' "$GITHUB_EVENT_PATH")
        issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
        issue_body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
        issue_updated_at=$(jq -r '.issue.updated_at' "$GITHUB_EVENT_PATH")
        
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $FEISHU_APP_TOKEN" \
        -d "{\"fields\":{\"IssueNumber\":\"$issue_number\",\"IssueAuthor\":\"$issue_author\",\"IssueCreatedTime\":\"$issue_created_at\",\"IssueStatus\":\"$issue_status\",\"IssueTitle\":\"$issue_title\",\"IssueDescription\":\"$issue_body\",\"LastModifiedTime\":\"$issue_updated_at\"}}" \
        https://open.feishu.cn/open-apis/bitable/v1/apps/$ISSUES_TABLE_ID/records
        
    - name: Sync Pull Requests to Feishu  
      if: github.event_name == 'pull_request'
      env:
        FEISHU_APP_TOKEN: ${{ steps.get_feishu_token.outputs.feishu_app_token }}
        PR_TABLE_ID: ${{ secrets.PR_TABLE_ID }}
      run: |
        pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        pr_author=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        pr_created_at=$(jq -r '.pull_request.created_at' "$GITHUB_EVENT_PATH")
        pr_status=$(jq -r '.pull_request.state' "$GITHUB_EVENT_PATH")
        pr_title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        pr_body=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        pr_updated_at=$(jq -r '.pull_request.updated_at' "$GITHUB_EVENT_PATH")
        
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $FEISHU_APP_TOKEN" \
        -d "{\"fields\":{\"PullRequestNumber\":\"$pr_number\",\"PullRequestAuthor\":\"$pr_author\",\"PullRequestCreatedTime\":\"$pr_created_at\",\"IssueStatus\":\"$pr_status\",\"PullRequestTitle\":\"$pr_title\",\"PullRequestDescription\":\"$pr_body\",\"LastModifiedTime\":\"$pr_updated_at\"}}" \
        https://open.feishu.cn/open-apis/bitable/v1/apps/$PR_TABLE_ID/records
