name: Sync GitHub Issues and Pull Requests to Feishu Table

on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, edited]

jobs:
  sync-to-feishu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get Feishu App Access Token
      id: get-feishu-token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"app_id\":\"$APP_ID\",\"app_secret\":\"$APP_SECRET\"}" \
        https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal | \
        jq -r '.tenant_access_token' > $GITHUB_OUTPUT
        
    - name: Sync Issue to Feishu
      if: github.event_name == 'issues'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ISSUES_TABLE_ID: ${{ secrets.ISSUES_TABLE_ID }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        ISSUE_CREATED_TIME: ${{ github.event.issue.created_at }}
        ISSUE_STATUS: ${{ github.event.issue.state }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        LAST_MODIFIED_TIME: ${{ github.event.issue.updated_at }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: Bearer $APP_TOKEN" \
        -d "{
          \"fields\": {
            \"IssueNumber\": \"$ISSUE_NUMBER\",
            \"IssueAuthor\": \"$ISSUE_AUTHOR\",
            \"IssueCreatedTime\": \"$ISSUE_CREATED_TIME\",
            \"IssueStatus\": \"$ISSUE_STATUS\",
            \"IssueTitle\": \"$ISSUE_TITLE\",
            \"IssueDescription\": \"$ISSUE_DESCRIPTION\",
            \"LastModifiedTime\": \"$LAST_MODIFIED_TIME\"
          }
        }" \
        https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$ISSUES_TABLE_ID/records
        
    - name: Sync Pull Request to Feishu  
      if: github.event_name == 'pull_request'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        PR_TABLE_ID: ${{ secrets.PR_TABLE_ID }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        PR_CREATED_TIME: ${{ github.event.pull_request.created_at }}
        PR_STATUS: ${{ github.event.pull_request.state }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        LAST_MODIFIED_TIME: ${{ github.event.pull_request.updated_at }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: Bearer $APP_TOKEN" \
        -d "{
          \"fields\": {
            \"PullRequestNumber\": \"$PR_NUMBER\",
            \"PullRequestAuthor\": \"$PR_AUTHOR\", 
            \"PullRequestCreatedTime\": \"$PR_CREATED_TIME\",
            \"IssueStatus\": \"$PR_STATUS\",
            \"PullRequestTitle\": \"$PR_TITLE\",
            \"PullRequestDescription\": \"$PR_DESCRIPTION\",
            \"LastModifiedTime\": \"$LAST_MODIFIED_TIME\"
          }
        }" \
        https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$PR_TABLE_ID/records
