name: Sync GitHub Issues and Pull Requests to Feishu Table

on:
  issues:
    types: [opened, closed, reopened, edited]
  pull_request:
    types: [opened, closed, reopened, edited]

jobs:
  sync-to-feishu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get Feishu App Access Token
      id: get_feishu_token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: |
        # Use APP_ID and APP_SECRET to get app_access_token
        app_access_token=$(curl -X POST -H 'Content-Type: application/json' \
          -d "{\"app_id\":\"$APP_ID\",\"app_secret\":\"$APP_SECRET\"}" \
          https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal)
        echo "::set-output name=app_access_token::$app_access_token"
        
    - name: Sync Issues to Feishu
      if: github.event_name == 'issues'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ISSUES_TABLE_ID: ${{ secrets.ISSUES_TABLE_ID }}
      run: |
        # Get issue details
        issue_number=${{ github.event.issue.number }}
        issue_author=${{ github.event.issue.user.login }}
        issue_created_at=${{ github.event.issue.created_at }}
        issue_status=${{ github.event.issue.state }}
        issue_title=${{ github.event.issue.title }}
        issue_body=${{ github.event.issue.body }}
        issue_updated_at=${{ github.event.issue.updated_at }}
        
        # Create record in Feishu table
        curl -X POST \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $APP_TOKEN" \
          -d "{
            \"fields\": {
              \"IssueNumber\": \"$issue_number\",
              \"IssueAuthor\": \"$issue_author\",
              \"IssueCreatedTime\": \"$issue_created_at\",
              \"IssueStatus\": \"$issue_status\",
              \"IssueTitle\": \"$issue_title\",
              \"IssueDescription\": \"$issue_body\",
              \"LastModifiedTime\": \"$issue_updated_at\"
            }
          }" \
          https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$ISSUES_TABLE_ID/records
          
    - name: Sync Pull Requests to Feishu  
      if: github.event_name == 'pull_request'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        PR_TABLE_ID: ${{ secrets.PR_TABLE_ID }}
      run: |
        # Get pull request details
        pr_number=${{ github.event.pull_request.number }}
        pr_author=${{ github.event.pull_request.user.login }}
        pr_created_at=${{ github.event.pull_request.created_at }}
        pr_status=${{ github.event.pull_request.state }}
        pr_title=${{ github.event.pull_request.title }}
        pr_body=${{ github.event.pull_request.body }}
        pr_updated_at=${{ github.event.pull_request.updated_at }}
        
        # Create record in Feishu table
        curl -X POST \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $APP_TOKEN" \
          -d "{
            \"fields\": {
              \"PullRequestNumber\": \"$pr_number\",
              \"PullRequestAuthor\": \"$pr_author\",
              \"PullRequestCreatedTime\": \"$pr_created_at\",
              \"IssueStatus\": \"$pr_status\",
              \"PullRequestTitle\": \"$pr_title\",
              \"PullRequestDescription\": \"$pr_body\",
              \"LastModifiedTime\": \"$pr_updated_at\"
            }
          }" \
          https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$PR_TABLE_ID/records
