name: Sync GitHub Issues and Pull Requests to Feishu Table

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  sync-to-feishu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Get Feishu App Access Token
      id: get_feishu_token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: |
        # Use APP_ID and APP_SECRET to get app_access_token
        app_access_token=$(curl -X POST -H 'Content-Type: application/json' \
          -d "{\"app_id\":\"$APP_ID\",\"app_secret\":\"$APP_SECRET\"}" \
          https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal | jq -r '.tenant_access_token')
        echo "app_access_token=$app_access_token" >> $GITHUB_OUTPUT
        
    - name: Sync Issues to Feishu
      if: github.event_name == 'issues'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ISSUES_TABLE_ID: ${{ secrets.ISSUES_TABLE_ID }}
      run: |
        issue_number=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        issue_author=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
        issue_created_at=$(jq -r '.issue.created_at' "$GITHUB_EVENT_PATH")
        issue_status=$(jq -r '.issue.state' "$GITHUB_EVENT_PATH")
        issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
        issue_description=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
        
        # Use APP_TOKEN and ISSUES_TABLE_ID to create a new record in the Feishu table
        curl -X POST -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $APP_TOKEN" \
          -d "{\"fields\":{\"IssueNumber\":\"$issue_number\",\"IssueAuthor\":\"$issue_author\",\"IssueCreatedTime\":\"$issue_created_at\",\"IssueStatus\":\"$issue_status\",\"IssueTitle\":\"$issue_title\",\"IssueDescription\":\"$issue_description\"}}" \
          https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$ISSUES_TABLE_ID/records
          
    - name: Sync Pull Requests to Feishu  
      if: github.event_name == 'pull_request'
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        PR_TABLE_ID: ${{ secrets.PR_TABLE_ID }}
      run: |
        pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        pr_author=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        pr_created_at=$(jq -r '.pull_request.created_at' "$GITHUB_EVENT_PATH")
        pr_status=$(jq -r '.pull_request.state' "$GITHUB_EVENT_PATH")
        pr_title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        pr_description=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        
        # Use APP_TOKEN and PR_TABLE_ID to create a new record in the Feishu table
        curl -X POST -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $APP_TOKEN" \
          -d "{\"fields\":{\"PullRequestNumber\":\"$pr_number\",\"PullRequestAuthor\":\"$pr_author\",\"PullRequestCreatedTime\":\"$pr_created_at\",\"IssueStatus\":\"$pr_status\",\"PullRequestTitle\":\"$pr_title\",\"PullRequestDescription\":\"$pr_description\"}}" \
          https://open.feishu.cn/open-apis/bitable/v1/apps/$APP_TOKEN/tables/$PR_TABLE_ID/records
